# Site
title: ライデンの新人ブログ
subtitle:
description: 株式会社ライデンの新人社員による、日常の日々を綴るブログです。
author: ライデンの新人
timezone: Japan

# URL
url: https://ryden-inc.github.io/rookies
root: /rookies/
permalink: posts/:title.html

# Directory
skip_render:
  - circle.yml
  - demos/**/*

# Date / Time format
date_format: MMM D, YYYY

# Pagination
per_page: 0

# Extensions
theme: ryden-rookies
stylus:
  compress: true

# Deployment
deploy:
  type: git
  repo: https://github.com/ryden-inc/rookies.git
  branch: gh-pages
